config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category <ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase}

  has_many :articles, dependent: :destroy

  validates :username, 
                  presence: true,
                  uniqueness: { case_sensitive: false },
                  length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
                  presence: true,
                  uniqueness: { case_sensitive: false },
                  length: {maximum: 105},
                  format: { with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
 

  def index
    @articles = Article.all
    @users = User.all
  end

  def create
    @article = Article.new(params.require(:articles).permit(:title, :description))
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was saved successfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = "Article was updated successfuly"
      redirect_to '/articles'
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:notice] = "Article was deleted successfully"
    end
    redirect_to '/articles'
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category Created Successfully"
            redirect_to @category
        else
            render 'new'
        end
    end

    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only Admins Can Perform That Action"
            redirect_to categories_path
        end 
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged In Successfully"
      redirect_to user
    else
      flash.now[:alert] = "There Was Something Wrong With Your Login Details"
      render 'new'
    end 
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully Logged Out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username} to the Alpha Blog, you have signed up successfully"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
    @articles = Article.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile Updations Were Made Successfuly"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    if(@user.destroy)
      session[:user_id] = nil
      flash[:notice] = "#{@user.username}'s Account Has Been Removed"
    end
    redirect_to articles_path
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with scope: :articles, url: articles_path, local: true do |f| %>
  
  <div class="form-group row">
    <%= f.label :Title, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :title, class: "form-control", placeholder: "enter title" %>
    </div>

    <%= f.label :Description, class: "col-2 col-form-label mt-2 "%>
    <div class="col-10">
      <%= f.text_area :description, rows: 10, class: "form-control mt-2", placeholder: "add description" %>
    </div>
  </div>

  <div class="form-group row justify-content-center mt-3">
    <%=f.submit class: "btn btn-outline-light btn-lg"%>
  </div>

<% end %>

app/views/articles/edit.html.erb
<div id="page-content">
  <div class="container" id="index-container">
    <h1 class="text-center mt-4"><strong>Article Editing</strong></h1>
    <%= render 'shared/error', obj: @article %>
    <div class="shadow p-3 mb-5 bg-info rounded text-center">
      <%= form_with(model: @article, local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :Title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control" %>
          </div>
      
          <p></p>
          
          <%= f.label :Description, class: "col-2 col-form-label mt-2"%>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control mt-2" %>
          </div>
        </div>
        
        <div class="form-group row justify-content-center mt-3">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
        
      <% end %>
    </div> 
    
    <p></p>
    <div class="text-center">
      <a href="/articles">[ Cancel and return to articles listing ]</a>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div id="page-content">
  <div class="container" id="index-container">
  <h1 class="text-center mt-4">Listing all articles</h1>
  

  <% @articles.each do |articleData| %>
    <div>
      <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header">
      <em>by <%=@users.find(articleData.user_id).username%></em>
      </div>
      <div class="card-body">
        <h5 class="card-title"><strong><%=articleData.title%></strong></h5>
        <p class="card-text"><%=articleData.description%></p>
        <a href="/articles/<%=articleData.id%>" class="btn btn-outline-success" >View</a>

        <% if (logged_in? && (articleData.user_id == session[:user_id]))%>
          <a href="/articles/<%=articleData.id%>/edit" class="btn btn-outline-primary">Edit</a>
          <div class="btn btn-outline-danger">
            <%= link_to 'Delete', article_path(articleData), method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
        <% end %>
        
      </div>
      <div class="card-footer text-muted">
        <small><p>Created about <%=time_ago_in_words(articleData.created_at)%> ago,  
                  Edited about <%=time_ago_in_words(articleData.updated_at)%> ago</p></small>
      </div>
      </div>
      <div id="spacing">
      </div>
      </div>
  <% end %>
  
  </div>
</div>

app/views/articles/new.html.erb
<div id="page-content">
  <div class="container" id="index-container">
    <h1 class="text-center mt-4"><strong>Adding A New Article</strong></h1>
      <%= render 'shared/error', obj: @article %>
    <div class="shadow p-3 mb-5 bg-info rounded text-center">
      <%= render 'form' %>
    </div>

    <p></p>
    <div class="text-center">
      <a href="/articles">[ Cancle and return to articles listing ]</a>
    </div>
  </div>
</div>

  

app/views/articles/show.html.erb
<h1>Showing Article Details</h1>

<div>
  <p><Strong>Title: </Strong><%=@article.title%></p>
  <p><Strong>Description: </Strong><%=@article.description%></p>
</div>



<p></p>
<div>

  <% if (logged_in? && (@article.user_id == session[:user_id]))%>
    <a href="/articles/<%=@article.id%>/edit">Edit</a> |
    <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %> |
  <% end %>
  <a href="/articles">Return To Article Listing</a>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |f| %>
  
  <div class="form-group row">
    <%= f.label :Name, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control", placeholder: "category name" %>
    </div>
  </div>

  <div class="form-group row justify-content-center mt-3">
    <%=f.submit class: "btn btn-outline-light btn-lg"%>
  </div>

<% end %>

app/views/categories/index.html.erb
<div id="page-content">
  <div class="container" id="index-container">
    <h1 class="text-center mt-4">Listing all Categories</h1>

    <% @categories.each do |cat|%>
      
      <div>
      <div class="card text-center shadow mb-5 bg-white rounded">
      
      <div class="card-body">
        <h5 class="card-title"><strong><%=cat.name%></strong></h5>
        <p class="card-text"></p>
        <a href="/categories/<%=cat.id%>" class="btn btn-outline-success" >View</a>
      </div>

      <div class="card-footer text-muted">
        <small><p>Created about <%=time_ago_in_words(cat.created_at)%> ago,  
                  Edited about <%=time_ago_in_words(cat.updated_at)%> ago</p></small>
      </div>
      
      </div>
      <div id="spacing">
      </div>
      </div>

    <%end%>

    
</div>

app/views/categories/new.html.erb
<div id="page-content">
<div class="container" id="index-container">
  <h1 class="text-center mt-4"><strong>Create A New Category</strong></h1>
  <%= render 'shared/error', obj: @category %>
  <div class="shadow p-3 mb-5 bg-info rounded text-center">
    <%= render 'form' %>
  </div>

  <p></p>
  <div class="text-center">
    <a href="<%=root_path%>">[ Cancle and return to Home Page ]</a>
  </div>
</div>
</div>

app/views/categories/show.html.erb
<div id="page-content">
  <div class="container" id="index-container">
    <h1 class="text-center mt-4"><%=@category.name%> Articles</h1>
  

  </div>
</div>

app/views/layouts/_msg.html.erb
<% flash.each do |name, msg| %>
  <div class="container">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>  
<% end %>
<%= yield %>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" id="logo" href="/">AlphaBlog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/users">Bloggers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/articles">Articles Index</a>
          </li>
          <li class="nav-item">
            <%= link_to "Categories", categories_path, class: "nav-link" %>
          </li>
          <% if logged_in? %>
            <% if current_user.admin?%>
              <li class="nav-item">
                <%= link_to "Add Category", new_category_path, class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to "New Article", new_article_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log in', login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', signup_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  </head>

  <body class="d-flex flex-column">

    <%= render 'layouts/navigation' %>  
    <%= render 'layouts/msg' %>
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Alpha Blog</h1>

<a href="/">Home</a>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center">
      <h1 class="display-4">Alpha Blog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <a class="btn btn-success btn-lg" href="<%=signup_path%>" role="button">Sign up!</a>
    </div>
  </div>
</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h3>Following errors prevented the article from being saved</h3>
    <hr>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  
  <div class="form-group row">
    <%= f.label :Username, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :username, class: "form-control", placeholder: "username" %>
    </div>

    <%= f.label :Email, class: "col-2 col-form-label mt-2 "%>
    <div class="col-10">
      <%= f.email_field :email, class: "form-control mt-2", placeholder: "enter your email" %>
    </div>

    <%= f.label :Password, class: "col-2 col-form-label mt-2 "%>
    <div class="col-10">
      <%= f.password_field :password, class: "form-control mt-2", placeholder: "" %>
    </div>
  </div>

  <div class="form-group row justify-content-center mt-3">
    <%=f.submit class: "btn btn-outline-light btn-lg"%>
  </div>

<% end %>

app/views/users/edit.html.erb
<div id="page-content">
<div class="container" id="index-container">
  <h1 class="text-center mt-4"><strong>Edit Your Profile</strong></h1>
    <%= render 'shared/error', obj: @user %>
  <div class="shadow p-3 mb-5 bg-info rounded text-center">
    <%= render 'form' %>
  </div>

  <p></p>
  <div class="text-center">
    <a href="<%=articles_path%>">[ Cancle and return to Articles listing ]</a>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div id="page-content">
  <div class="container" id="index-container">
  <h1 class="text-center mt-4">Alpha Bloggers</h1>

  <% @users.each do |userData| %>
    <div>
      <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header">
      <strong><%=userData.username%></strong>
      </div>
      <div class="card-body">
        <h5 class="card-title"><strong><%=userData.email%></strong></h5>

        <p class="card-text"><%=userData.articles.count%> Article(s)</p>

        <a href="<%=user_path(userData)%>" class="btn btn-outline-success" >View Profile</a>
        <%if(current_user == nil)%>
          <% if (logged_in? && (userData.id == session[:user_id]) || false) %>
            <a href="<%=edit_user_path(userData)%>" class="btn btn-outline-primary">Edit Profile</a>
          <% end %>
        <%else%>
          <% if (logged_in? && (userData.id == session[:user_id]) || current_user.admin?) %>
            <a href="<%=edit_user_path(userData)%>" class="btn btn-outline-primary">Edit Profile</a>
          <% end %>
        <%end%>
        
      </div>
      <div class="card-footer text-muted">
        <small><p>Joined <%=time_ago_in_words(userData.created_at)%> ago</p></small>
      </div>
      </div>
      <div id="spacing">
      </div>
      </div>
  <% end %>

  </div>
</div>

app/views/users/new.html.erb
<div id="page-content">
<div class="container" id="index-container">
  <h1 class="text-center mt-4"><strong>Sign Up For Alpha Blog</strong></h1>
    <%= render 'shared/error', obj: @user %>
  <div class="shadow p-3 mb-5 bg-info rounded text-center">
    <%= render 'form' %>
  </div>

  <p></p>
  <div class="text-center">
    <a href="<%=articles_path%>">[ Cancle and return to articles listing ]</a>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div id="page-content">
  <div class="container" id="index-container">
    <h1 class="text-center mt-4"><%=@user.username%>'s Profile</h1>
    <div>
      <h5 class="text-center mt-5"><%=@user.email%></h3>
      <% if (logged_in? && (@user.id == session[:user_id])) %>
        <div class="text-center mt-4">
          <a href="<%=edit_user_path(@user)%>" class="btn btn-outline-primary">Edit Your Profile</a>
          <div class="btn btn-outline-danger">
            <%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: "Remove Your Account?"} %>
          </div>
        </div>
      <% end %>

    </div>

    <div><h2 class="text-center mt-3">Articles</h2></div>

    <% @articles.each do |articleData| %>
      <%if (articleData.user_id == @user.id)%>
        <div>
        <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header">
        <em>by <%=@user.username%></em>
        </div>
        <div class="card-body">
          <h5 class="card-title"><strong><%=articleData.title%></strong></h5>
          <p class="card-text"><%=articleData.description%></p>
          <a href="/articles/<%=articleData.id%>" class="btn btn-outline-success" >View</a>
          <% if (logged_in? && (@user.id == session[:user_id])) %>
            <a href="/articles/<%=articleData.id%>/edit" class="btn btn-outline-primary">Edit</a>
            <div class="btn btn-outline-danger">
              <%= link_to 'Delete', article_path(articleData), method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
          <% end %>

        </div>
        <div class="card-footer text-muted">
          <small><p>Created about <%=time_ago_in_words(articleData.created_at)%> ago,  
                    Edited about <%=time_ago_in_words(articleData.updated_at)%> ago</p></small>
        </div>
        </div>
        <div id="spacing">
        </div>
        </div>
      <%end%>
    <% end %>
  


  </div>
</div>